name: Devops demo pipline

on:
    push:
        branches:
            - main

jobs:
    runner-info:
        runs-on: ubuntu-latest

        steps:
            - name: CheckOut
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Check Node Version
              run: node -v

            - name: Check NPM Version
              run: npm -v

            - name: Run application
              env:
                  NODE_ENV: production
                  APP_NAME: DevOps Demo App
                  APP_VERSION: v1.0.0

              run: node app.js

            - name: Install Depdencies
              run: npm ci

            - name: Show Installed Packages
              run: npm list
