name: Devops demo pipline

on:
    push:
        branches:
            - main

jobs:
    runner-ifo:
        runs-on: ubuntu-latest

        steps:
            - name: Print message
              run: date

            - name: Print current user
              run: whoami

            - name: Print working directory
              run: pwd

            - name: Show OS Information
              run: uname -a

            - name: List Files
              run: ls -la
